### ISSUE TITLE
DDColor working Deoldify not working

### ISSUE THREAD

**Issue by TechHalloman** [dan64/vs-deoldify#1]
software  worked  at  windows 11 . DDColor working Deoldify not working 

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta charset="utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
hr { height: 1px; border-width: 0; }
li.unchecked::marker { content: "\2610"; }
li.checked::marker { content: "\2612"; }
</style></head><body>

2024-03-22 13:41:10.438 Failed to evaluate the script:Python exception: ddeoldify() got an unexpected keyword argument 'chroma_resize'Traceback (most recent call last):File "src\cython\vapoursynth.pyx", line 3115, in vapoursynth._vpy_evaluateFile "src\cython\vapoursynth.pyx", line 3116, in vapoursynth._vpy_evaluateFile "C:\Users\SOS\AppData\Local\Temp\tempPreviewVapoursynthFile13_40_57_183.vpy", line 30, in clip = ddeoldify(clip=clip, model=0, sat=[1.00,1], hue=[0.00,0], chroma_resize=False)^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^TypeError: ddeoldify() got an unexpected keyword argument 'chroma_resize'
--

</body></html>

**Comment by dan64** [comment]
The parameter chroma_resize was added in the version 2.0.0, please upgrade to the last version.

**Comment by TechHalloman** [comment]
working with latest Hybrid and addon
